### ISSUE TITLE
Handle ro-crate-metadata.json as well as jsonld

### ISSUE THREAD

**Issue by marcolarosa** [UTS-eResearch/ro-crate-js#3]
I'm using this library in describo and describo writes the file `ro-crate-metadata.json` and not `ro-crate-metadata.jsonld`. Likewise, the crate metadata object has `ro-crate-metadata.json`:

```
{
      "@id": "/ro-crate-metadata.json",
      "@type": "CreativeWork",
      "about": {
        "@id": "./"
      },
      "identifier": "ro-crate-metadata.json",
      "conformsTo": {
        "@id": "https://w3id.org/ro/crate/1.0"
      },
      "license": {
        "@id": "https://creativecommons.org/licenses/by-sa/3.0"
      },
      "description": "Made with Describo: https://uts-eresearch.github.io/describo/"
    },
```

When I try to create the html preview using:

```
        const preview = new Preview(crate);
```

The library fails with: `"Error: There is no pointer to the root dataset"` which i think is due to the metadata descriptor being .json instead of .jsonld.

@ptsefton said that it's changing to .json instead of jsonld but I just looked at the draft 1.1. spec and it still references .jsonld so maybe he needs to weigh in here.

**Comment by ptsefton** [comment]
Fixed it.
